# Generated by Django 5.1 on 2024-08-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons",
            name="video",
            field=models.URLField(
                blank=True,
                help_text="Загрузите видео урока",
                max_length=300,
                null=True,
                verbose_name="Видео урока",
            ),
        ),
    ]
